# http://travis-ci.org/#!/ipython/ipython
language: python
python:
    - 3.5
before_install:
    - pip install docutils
script:
    - make
after_success:
    - git stash pop
    - bash .travis/travis.sh
